# Generated by Django 2.2 on 2020-01-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hello',
            field=models.TextField(default=True),
        ),
    ]
